// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ContactManage: typeof import('./src/components/ContactManage/index.vue')['default']
    ContactScene: typeof import('./src/components/ContactScene/index.vue')['default']
    ContactSider: typeof import('./src/components/ContactSider/index.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    DispatchArea: typeof import('./src/components/DispatchArea/index.vue')['default']
    DispatchCard: typeof import('./src/components/DispatchCard.vue')['default']
    DispatchSider: typeof import('./src/components/DispatchSider/index.vue')['default']
    DispatchVoice: typeof import('./src/components/DispatchVoice/index.vue')['default']
    GisMap: typeof import('./src/components/GisMap/index.vue')['default']
    GisSider: typeof import('./src/components/GisSider/index.vue')['default']
    HandleArea: typeof import('./src/components/HandleArea.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm/index.vue')['default']
    MonitorPlayback: typeof import('./src/components/MonitorPlayback/index.vue')['default']
    MonitorRound: typeof import('./src/components/MonitorRound/index.vue')['default']
    MonitorSider: typeof import('./src/components/MonitorSider/index.vue')['default']
    MonitorVideo: typeof import('./src/components/MonitorVideo/index.vue')['default']
    MonitorWall: typeof import('./src/components/MonitorWall/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopUtils: typeof import('./src/components/TopUtils.vue')['default']
  }
}

export {}
